apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: wsi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fargate
      version: blue
  template:
    metadata:
      namespace: demo
      labels:
        app: fargate
        version: blue
    spec:
      containers:
        - name: nginx
          image: nginx:latest